
export const nullValues = {
  companyName: "",
  companyAddress: "",
  state: "",
  district: "",
  authorizedPersonName: "",
  authorizedContactNumber: "",
  companyEmailId: "",
  panNumber: "",
  gstNumber: "",
  epfCodeNumber: "",
  esicCodeNumber: "",
  professionalTax: "",
  tanNumber: "",
  workPlaceName: "",
  serviceProvide: "With Register",
  dateOfCommencement: "",
  licenceNumber: "",
  epfRegionalName: "",
  esicRegionalName: "",
  natureOfBusiness: "",
  professionalFees: "",
};
export const modifyNullValues = {
  companyAddress: "",
  state: "",
  district: "",
  authorizedPersonName: "",
  authorizedContactNumber: "",
  companyEmailId: "",
  panNumber: "",
  gstNumber: "",
  epfCodeNumber: "",
  esicCodeNumber: "",
  professionalTax: "",
  tanNumber: "",
  workPlaceName: "",
  serviceProvide: "With Register",
  dateOfCommencement: "",
  licenceNumber: "",
  epfRegionalName: "",
  esicRegionalName: "",
  natureOfBusiness: "",
  professionalFees: "",
};

