export const inputs = [
    {
      id: 1,
      name: "employeeName",
      type: "text",
      placeholder: "employeeName",
      label: "Employee Name",
      required: true,
    },
    {
      id: 2,
      name: "fatherName",
      type: "text",
      placeholder: "fatherName",
      label: "Father Name",
      required: true,
    },
    {
      id: 3,
      name: "dateOfBirth",
      type: "date",
      placeholder: "Date Of Birth",
      label: "Date Of Birth",
      required: true,
    },
    {
      id: 4,
      name: "gender",
      type: "text",
      placeholder: "gender",
      label: "Gender",
    },
    {
      id: 5,
      name: "maritalStatus",
      type: "text",
      placeholder: "maritalStatus",
      label: "Marital Status",
    },
    {
      id: 6,
      name: "dateOfJoining",
      type: "date",
      placeholder: "dateOfJoining",
      label: "Date Of Joining",
    },
    {
      id: 7,
      name: "designation",
      type: "text",
      placeholder: "designation",
      label: "Designation",
    },
    {
      id: 8,
      name: "department",
      type: "text",
      placeholder: "department",
      label: "Department",
    },
    {
      id: 9,
      name: "dateOfLeaving",
      type: "date",
      placeholder: "dateOfLeaving",
      label: "Date Of Leaving ( if Exit )",
    },
    {
      id: 10,
      name: "address",
      type: "textarea",
      placeholder: "address",
      label: "Address",
    },
    {
      id: 11,
      name: "contactNumber",
      type: "number",
      placeholder: "Contact Number",
      label: "Contact Number",
    },
    {
      id: 12,
      name: "email",
      type: "email",
      placeholder: "Email",
      label: "Email",
    },
    {
      id: 16,
      name: "nomineeName",
      type: "text",
      placeholder: "nomineeName",
      label: "Nominee Name",
    },
    {
      id: 17,
      name: "relationshipWithMember",
      type: "text",
      placeholder: "relationshipWithMember",
      label: "Relationship With Member",
    },

  ];
  
  export const nullValues = {
    employeeName: "",
    fatherName: "",
    dateOfBirth: "",
    gender: "",
    maritalStatus:"",
    dateOfJoining: "",
    designation: "",
    department: "",
    dateOfLeaving: "",
    address: "",
    contactNumber: "",
    email: "",
    uidAadharNumber: "",
    nomineeName: "",
    relationshipWithMember: "",
    }
  
  export const additionalNullValues = {
    kycDetails:{
      aadharNumber:"",
      nameAsPerAadhar:"",
      dateOfBirthAsPerAadhar:"",
      panNumber:"",
      mobileNumber:"",
      otherDetails:"",
      },
      financialDetails:{
        bankName:"",
        bankBranch:"",
        accountNumber:"",
        ifscCode:"",
        rest:"",
        calculation:"",
      },
      salaryDetails:{
        epfMemberId:"",
        uanNumber:"",
        esicIpNumber:"",
        bonusApplicable:"",
        gratuityApplicable:"",
        otherDetails:"",
      }
    }
    
    export const KycInputs = [
      {
        id: 1,
        name: "aadharNumber",
        type: "text",
        placeholder: "aadharNumber",
        label: "aadhar Number",
        required: true,
      },
      {
        id: 2,
        name: "nameAsPerAadhar",
        type: "text",
        placeholder: "nameAsPerAadhar",
        label: "name As Per Aadhar",
        required: true,
      },
      {
        id: 3,
        name: "dateOfBirthAsPerAadhar",
        type: "date",
        placeholder: "As Per Aadhar",
        label: "Date Of Birth",
        required: true,
      },
      {
        id: 4,
        name: "panNumber",
        type: "text",
        placeholder: "panNumber",
        label: "Pan Number",
      },
      {
        id: 5,
        name: "mobileNumber",
        type: "text",
        placeholder: "mobileNumber",
        label: "Mobile Number",
      },
      {
        id: 6,
        name: "otherDetails",
        type: "text",
        placeholder: "Other Details",
        label: "Other Details",
      },
    ]
    export const financialInputs = [
      {
        id: 1,
        name: "bankName",
        type: "text",
        placeholder: "bankName",
        label: "Bank Name",
        required: true,
      },
      {
        id: 2,
        name: "bankBranch",
        type: "text",
        placeholder: "bankBranch",
        label: "Bank Branch",
        required: true,
      },
      {
        id: 3,
        name: "accountNumber",
        type: "number",
        placeholder: "Account Number",
        label: "Account Number",
        required: true,
      },
      {
        id: 4,
        name: "ifscCode",
        type: "text",
        placeholder: "ifscCode",
        label: "ifscCode",
      },
      
    ]
    export const salaryInputs = [
      // epfMemberId:"",
      // uanNumber:"",
      // esicIpNumber:"",
      // bonusApplicable:"",
      // gratuityApplicable:"",
      // otherDetailsIfAny:[""],
      {
        id: 1,
        name: "epfMemberId",
        type: "text",
        placeholder: "EPF MemberId",
        label: "EPF Member Id",
        required: true,
      },
      {
        id: 2,
        name: "uanNumber",
        type: "text",
        placeholder: "Uan Number",
        label: "Uan Number",
        required: true,
      },
      {
        id: 3,
        name: "esicIpNumber",
        type: "number",
        placeholder: "Esic Ip Number",
        label: "Esic Ip Number",
      },
      {
        id: 4,
        name: "bonusApplicable",
        type: "text",
        placeholder: "Bonus Applicable",
        label: "Bonus Applicable",
      },
      {
        id: 5,
        name: "gratuityApplicable",
        type: "text",
        placeholder: "Gratuity Applicable",
        label: "Gratuity Applicable",
      },
      {
        id: 6,
        name: "otherDetails",
        type: "text",
        placeholder: "Other Details",
        label: "Other Details",
      },
    ]